# Generated by Django 5.2.8 on 2025-11-27 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_featured_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'approved', 'created_date'], name='blog_commen_post_id_1aea25_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['approved', 'created_date'], name='blog_commen_approve_74167e_idx'),
        ),
    ]
