# Generated by Django 5.2.10 on 2026-01-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_create_date_post_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='content_idx',
        ),
    ]
